### ISSUE TITLE
Failed to compile when I switch from 1.0.2 to 1.0.5 with the library @calcom/embed-react in a typescript project

### ISSUE THREAD

**Issue by aayestashn** [calcom/cal.com#2858]
### Issue Summary

I am experimenting the following issue with the library @calcom/embed-react when I updated from version 1.0.2 to 1.0.5 in an Ionic v6 project with react 17.

```
/Users/astorayestas/Documents/180msk/node_modules/@calcom/embed-snippet/src/index.ts
TypeScript error in /Users/astorayestas/Documents/180msk/node_modules/@calcom/embed-snippet/src/index.ts(5,64):
Cannot find module '@calcom/embed-core/src/embed' or its corresponding type declarations.  TS2307

    3 |  * So, write the code that you need directly but keep it short.
    4 |  */
  > 5 | import { Cal as CalClass, Instruction, InstructionQueue } from "@calcom/embed-core/src/embed";
      |                                                                ^
    6 | 
    7 | export interface GlobalCal {
    8 |   (methodName: string, arg?: any): void;
```
### Steps to Reproduce

1. Update the package @calcom/embed-react from 1.0.2 to 1.0.5

### Technical details

- Ionic with react application
- "@ionic/react": "^6.1.2",
- "react-dom": "^17.0.1",
- "react": "^17.0.1",
- "typescript": "^4.1.3",
- Node.js Version: v16.14.2

**Comment by hariombalhara** [comment]
@aayestashn Can you try `@calcom/embed-react@1.0.6-beta.4`. 
It should be fixed in it.

**Comment by aayestashn** [comment]
@hariombalhara I made a couple of tests and work perfectly. 👏🏽

**Comment by hariombalhara** [comment]
Awesome! Thanks for confirmation. Will push it to stable soon.
