### PR TITLE
fix(lib): use Intl directly in timezoneConstants to avoid plugin-order crash

### LINKED ISSUE #29341: @calcom/atoms crashes in Next.js App Router beyond version 2.6.0
### Issue Summary

`@calcom/atoms@2.11.0` fails at runtime in a minimal Next.js App Router project when rendering the Booker atom from a client-only modal.

The same repro works on `@calcom/atoms@2.6.0`. The only intended difference between the working and failing branches is the package version and resulting lockfile changes.

Repro repo: https://github.com/mogusbi-motech/cal-com-atom-bundling-issue

Failing branch using `@calcom/atoms@2.11.0`:
https://github.com/mogusbi-motech/cal-com-atom-bundling-issue/tree/main

Working comparison branch using `@calcom/atoms@2.6.0`:
https://github.com/mogusbi-motech/cal-com-atom-bundling-issue/tree/working-2.6.0

The current failure appears to come from `@calcom/atoms/dist/vendor/timezone-constants.js`, which evaluates `dayjs.tz.guess()` before `dayjs.tz` is available.

### Steps to Reproduce

1. Clone the repro:

   ```bash
   git clone https://github.com/mogusbi-motech/cal-com-atom-bundling-issue.git
   cd cal-com-atom-bundling-issue
   ```

2. Check out the failing branch:

   ```bash
   git checkout main
   ```

3. Install dependencies:

   ```bash
   pnpm install
   ```

4. Start the app:

   ```bash
   pnpm dev
   ```

5. Open the local Next.js URL.

6. Submit the form with valid Cal.com values:
   - Client ID
   - API URL, for example `https://api.cal.com/v2`
   - Username
   - Event slug

7. Click `Open calendar modal`.

For comparison, the same flow works on:

```bash
git checkout working-2.6.0
pnpm install
pnpm dev
```

### Actual Results

- The calendar modal fails to load on `@calcom/atoms@2.11.0`.
- The browser shows:

```text
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'guess')

Call Stack
eval
node_modules/@calcom/atoms/dist/vendor/timezone-constants.js (4:21)
```

Before reaching this error, `2.11.0` also required adding Stripe packages because the top-level Atoms import pulls in payment modules:

```text
Module not found: Can't resolve '@stripe/react-stripe-js'
```

Installing the Stripe dependencies resolves that module-resolution error, but the timezone runtime error remains.

### Expected Results

- Importing and rendering `CalProvider` and `Booker` from `@calcom/atoms` should render the Booker atom successfully.
- Optional payment modules should not be required when the consuming app is not using payments.
- Package modules should not evaluate browser/runtime-sensitive values at module scope in a way that crashes before Booker renders.

### Technical details

- Repro repo: https://github.com/mogusbi-motech/cal-com-atom-bundling-issue
- Failing branch: `main`
- Working branch: `working-2.6.0`
- Failing package version: `@calcom/atoms@2.11.0`
- Working package version: `@calcom/atoms@2.6.0`
- Next.js: `14.2.35`
- React: `18.3.1`
- Node.js: `v24.14.1`
- pnpm: `11.1.0`

During incremental upgrade testing, these version ranges showed different failures:

| Version range | Observation |
| --- | --- |
| `2.6.0` | Works. |
| `2.7.0` to `2.8.2` | Router/search-params runtime issue in the Booker path, with a failure like `Cannot read properties of null (reading 'get')`. |
| `2.8.3` to `2.8.9` | Runtime failure from `react-use/lib/usePrevious`: `TypeError: react_use_lib_usePrevious__WEBPACK_IMPORTED_MODULE_3__ is not a function`. |
| `2.9.0` to `2.11.0` | Runtime failure from `dist/vendor/timezone-constants.js`: `Cannot read properties of undefined (reading 'guess')`. |

### Evidence

The repro contains two branches that should make the difference easy to verify:

- `main`: fails with `@calcom/atoms@2.11.0`
- `working-2.6.0`: works with `@calcom/atoms@2.6.0`

The README contains the same reproduction notes:
https://github.com/mogusbi-motech/cal-com-atom-bundling-issue/blob/main/README.md

### PR DESCRIPTION
**Pull request by spokodev**
Fixes #29341.

## Problem

`packages/lib/timezoneConstants.ts` evaluates `dayjs.tz.guess()` at module-load time:

\`\`\`ts
import dayjs from "@calcom/dayjs";

export const IS_EUROPE = dayjs.tz.guess()?.indexOf("Europe") !== -1;
export const CURRENT_TIMEZONE = dayjs.tz.guess() !== "Etc/Unknown" ? dayjs.tz.guess() : "Europe/London";
\`\`\`

When this file ends up in a vendor chunk that loads before `@calcom/dayjs/index.ts` has run `dayjs.extend(timezone)` — which is exactly what happens inside the bundled `@calcom/atoms` package from 2.7 onwards — `dayjs.tz` is undefined and the module crashes at import:

\`\`\`
TypeError: Cannot read properties of undefined (reading 'guess')
  at @calcom/atoms/dist/vendor/timezone-constants.js:4
\`\`\`

This is what the reporter in #29341 observed on a minimal Next.js App Router project rendering `<Booker />` from `@calcom/atoms@2.11.0`.

## Fix

Use `Intl.DateTimeFormat().resolvedOptions().timeZone` directly. This is the same browser/Node API that `dayjs.tz.guess()` wraps internally, so the runtime return value is identical for every locale, but it has no plugin dependency and is safe to call at module-eval time regardless of bundler chunk order.

The exports keep their `string` type, so no caller needs updating. The original code also called `.guess()` three times (once for `IS_EUROPE`, twice in the `CURRENT_TIMEZONE` ternary) — the rewrite caches the result once.

## Why this approach

- Aligns with the Cal.diy guideline "Use date-fns or native Date instead of Day.js when timezone awareness isn't needed". `Intl.DateTimeFormat` is part of the platform; we don't need Day.js for a simple `guess`.
- Removes a hidden dependency on plugin-extension order, which was the root cause of the crash. A fix that simply re-imports the timezone plugin inside `timezoneConstants.ts` would paper over the bundling fragility without solving it.
- Single-file change, 9+/3-, no consumer signature changes.

## Test plan

- `npx tsc --noEmit packages/lib/timezoneConstants.ts` — clean
- `npx biome lint packages/lib/timezoneConstants.ts` — pre-existing `noTernary` info inherited from the original code; no new warnings introduced
- Manual: reproducer repo from #29341 (https://github.com/mogusbi-motech/cal-com-atom-bundling-issue) should no longer crash at `timezone-constants.js:4` after this lands in a new `@calcom/atoms` release

### CODE REVIEW

**Comment by spokodev** [comment]
@CLAassistant recheck

**Comment by spokodev** [comment]
@CLAassistant recheck

**Comment by spokodev** [comment]
Still relevant. Will rebase on request from a reviewer.

**Comment by spokodev** [comment]
Still relevant. This one is only blocked on the `ready-for-e2e` label so the suite can run — could a maintainer add it when convenient? I can rebase first if you'd prefer. (Same situation on #29351 and #29405 if you want to batch the three.)

File: packages/lib/timezoneConstants.ts [hunk 1]
```diff
@@ -1,4 +1,10 @@
...
+// ends up in a vendor chunk that loads before `@calcom/dayjs/index.ts`
+// (e.g. inside the bundled `@calcom/atoms` package), `dayjs.tz` is undefined
+// and accessing `.guess()` crashes at module-eval time. `Intl.DateTimeFormat`
+// is what `dayjs.tz.guess()` wraps internally and has no plugin dependency.
+const guessedTimezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
 
-export const IS_EUROPE = dayjs.tz.guess()?.indexOf("Europe") !== -1;
-export const CURRENT_TIMEZONE = dayjs.tz.guess() !== "Etc/Unknown" ? dayjs.tz.guess() : "Europe/London";
+export const IS_EUROPE = guessedTimezone.indexOf("Europe") !== -1;
+export const CURRENT_TIMEZONE = guessedTimezone !== "Etc/Unknown" ? guessedTimezone : "Europe/London";
```
[the remark this answers is not in the document]
Comment (spokodev) [reply packages/lib/timezoneConstants.ts]: Both addressed: `guessedTimezone` already falls back to `"Europe/London"` when `resolvedOptions().timeZone` is undefined (so `.startsWith`/`.indexOf` can't throw), and the check is now `startsWith("Europe/")` instead of `indexOf("Europe")` — equivalent on all current IANA data but precise to the `Region/City` form.

**Comment by spokodev** [comment]
CodeRabbit's review here is resolved (it confirmed both the `|| "Europe/London"` fallback and the `startsWith("Europe/")` check are in place). The change is a one-file fix in `timezoneConstants.ts` and is ready to rebase. The only thing outstanding is the `ready-for-e2e` label so the suite can run.

**Comment by albertocubeddu** [comment]
+1 !!!!

**Comment by spokodev** [comment]
Still relevant — the fix itself is ready (one-file change in `timezoneConstants.ts`), it's only waiting on the `ready-for-e2e` label so the suite can run. Happy to rebase whenever. Same for #29351 / #29405 if batching helps.
